# Generated by Django 4.1.3 on 2022-11-23 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
